apiVersion: v1
kind: Service
metadata:
  name: hello-service
  namespace: hello-app
  labels:
    app: hello-app
spec:
  selector:
    app: hello-app
  ports:
    - protocol: TCP
      port: 8080        
      targetPort: 32777 
  type: NodePort

